package com.runtime.permissions.runtimepermissions.presenters.db.entities;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteColumn;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteType;
import com.runtime.permissions.runtimepermissions.presenters.db.tables.PermissionTable;

/**
 * Created by Евгений on 27.09.2015
 */
@StorIOSQLiteType(table = PermissionTable.TABLE)
public class Permission {
    @Nullable
    @StorIOSQLiteColumn(name = PermissionTable.COLUMN_ID, key = true)
    public Long id;

    @StorIOSQLiteColumn(name = PermissionTable.COLUMN_PERMISSION_NAME)
    public String permission;

    @StorIOSQLiteColumn(name = PermissionTable.COLUMN_IS_GRANTED)
    public Integer isGranted;

    @StorIOSQLiteColumn(name = PermissionTable.COLUMN_IS_NEED_TO_SHOW_REQUEST)
    public Integer isNeedToShowRequest;

    // leave default constructor for AutoGenerated code!
    Permission() {
    }

    private Permission(@Nullable Long id, @NonNull String permission, @NonNull Integer isGranted, @NonNull Integer isNeedToShowRequest) {
        this.id = id;
        this.permission = permission;
        this.isGranted = isGranted;
        this.isNeedToShowRequest = isNeedToShowRequest;
    }

    @NonNull
    public static Permission newPermission(@Nullable Long id, @NonNull String permission, @NonNull Integer isGranted, @NonNull Integer isNeedToShowRequest) {
        return new Permission(id, permission, isGranted, isNeedToShowRequest);
    }

    @NonNull
    public static Permission newPermission(@NonNull String permission, @NonNull Integer isGranted, @NonNull Integer isNeedToShowRequest) {
        return new Permission(null, permission, isGranted, isNeedToShowRequest);
    }
}
