package com.runtime.permissions.runtimepermissions.presenters.db.entities;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteColumn;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteType;
import com.runtime.permissions.runtimepermissions.presenters.db.tables.PermissionTable;

/**
 * Created by Евгений on 27.09.2015
 */
@StorIOSQLiteType(table = PermissionTable.TABLE)
public class Permission {
    @Nullable
    @StorIOSQLiteColumn(name = PermissionTable.COLUMN_ID, key = true)
    public Long id;

    @StorIOSQLiteColumn(name = PermissionTable.COLUMN_PERMISSION_NAME)
    public String permission;

    @StorIOSQLiteColumn(name = PermissionTable.COLUMN_STATE)
    public Integer state;

    // leave default constructor for AutoGenerated code!
    Permission() {
    }

    private Permission(@Nullable Long id, @NonNull String permission, @NonNull Integer state) {
        this.id = id;
        this.permission = permission;
        this.state = state;
    }

    @NonNull
    public static Permission newTableInfo(@Nullable Long id, @NonNull String permission, @NonNull Integer state) {
        return new Permission(id, permission, state);
    }

    @NonNull
    public static Permission newTableInfo(@NonNull String permission, @NonNull Integer state) {
        return new Permission(null, permission, state);
    }
}
